conformance_automated = "Fail"
errors_diff = """
Line 24: Expected 1 errors
Line 107: Expected 1 errors
Line 114: Expected 1 errors
Line 30: Unexpected errors ['generics_defaults.py:30:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`']
Line 31: Unexpected errors ['generics_defaults.py:31:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`']
Line 32: Unexpected errors ['generics_defaults.py:32:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`']
Line 38: Unexpected errors ['generics_defaults.py:38:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`']
Line 45: Unexpected errors ['generics_defaults.py:45:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`']
Line 46: Unexpected errors ['generics_defaults.py:46:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`']
Line 52: Unexpected errors ['generics_defaults.py:52:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`']
Line 55: Unexpected errors ['generics_defaults.py:55:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`']
Line 59: Unexpected errors ['generics_defaults.py:59:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`']
Line 63: Unexpected errors ['generics_defaults.py:63:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`']
Line 79: Unexpected errors ['generics_defaults.py:79:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`']
Line 80: Unexpected errors ['generics_defaults.py:80:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`']
Line 91: Unexpected errors ['generics_defaults.py:91:26: error[invalid-argument-type] `@Todo` is not a valid argument to `Generic`']
Line 94: Unexpected errors ['generics_defaults.py:94:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`']
Line 95: Unexpected errors ['generics_defaults.py:95:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`']
Line 127: Unexpected errors ['generics_defaults.py:127:32: error[invalid-return-type] Function always implicitly returns `None`, which is not assignable to return type `T4@func1`']
Line 151: Unexpected errors ['generics_defaults.py:151:12: error[invalid-argument-type] `@Todo` is not a valid argument to `Generic`']
Line 154: Unexpected errors ['generics_defaults.py:154:49: error[invalid-type-form] List literals are not allowed in this context in a type expression: Did you mean `tuple[int | float, bool]`?']
Line 155: Unexpected errors ['generics_defaults.py:155:58: error[invalid-type-form] List literals are not allowed in this context in a type expression: Did you mean `list[bytes]`?']
Line 169: Unexpected errors ['generics_defaults.py:169:1: error[type-assertion-failure] Argument does not have asserted type `(Foo7[int], /) -> Foo7[int]`']
"""
output = """
generics_defaults.py:30:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`
generics_defaults.py:31:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`
generics_defaults.py:32:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`
generics_defaults.py:38:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`
generics_defaults.py:45:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`
generics_defaults.py:46:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`
generics_defaults.py:50:1: error[missing-argument] No argument provided for required parameter `T2` of class `AllTheDefaults`
generics_defaults.py:52:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`
generics_defaults.py:55:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`
generics_defaults.py:59:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`
generics_defaults.py:63:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`
generics_defaults.py:79:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`
generics_defaults.py:80:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`
generics_defaults.py:91:26: error[invalid-argument-type] `@Todo` is not a valid argument to `Generic`
generics_defaults.py:94:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`
generics_defaults.py:95:1: error[type-assertion-failure] Argument does not have asserted type `@Todo`
generics_defaults.py:127:32: error[invalid-return-type] Function always implicitly returns `None`, which is not assignable to return type `T4@func1`
generics_defaults.py:141:12: error[invalid-argument-type] `@Todo` is not a valid argument to `Generic`
generics_defaults.py:151:12: error[invalid-argument-type] `@Todo` is not a valid argument to `Generic`
generics_defaults.py:154:49: error[invalid-type-form] List literals are not allowed in this context in a type expression: Did you mean `tuple[int | float, bool]`?
generics_defaults.py:155:58: error[invalid-type-form] List literals are not allowed in this context in a type expression: Did you mean `list[bytes]`?
generics_defaults.py:169:1: error[type-assertion-failure] Argument does not have asserted type `(Foo7[int], /) -> Foo7[int]`
"""
