conformance_automated = "Fail"
errors_diff = """
Line 43: Unexpected errors ['ERROR /Users/rob/dev/typing/conformance/tests/generics_self_advanced.py:43:20-39: assert_type(Any, list[Self]) failed [assert-type]', 'ERROR /Users/rob/dev/typing/conformance/tests/generics_self_advanced.py:43:21-26: Instance-only attribute `a` of class `ChildB` is not visible on the class [missing-attribute]']
Line 44: Unexpected errors ['ERROR /Users/rob/dev/typing/conformance/tests/generics_self_advanced.py:44:20-36: assert_type(Any, Self) failed [assert-type]', 'ERROR /Users/rob/dev/typing/conformance/tests/generics_self_advanced.py:44:21-26: Instance-only attribute `a` of class `ChildB` is not visible on the class [missing-attribute]']
"""
output = """
ERROR /Users/rob/dev/typing/conformance/tests/generics_self_advanced.py:43:20-39: assert_type(Any, list[Self]) failed [assert-type]
ERROR /Users/rob/dev/typing/conformance/tests/generics_self_advanced.py:43:21-26: Instance-only attribute `a` of class `ChildB` is not visible on the class [missing-attribute]
ERROR /Users/rob/dev/typing/conformance/tests/generics_self_advanced.py:44:20-36: assert_type(Any, Self) failed [assert-type]
ERROR /Users/rob/dev/typing/conformance/tests/generics_self_advanced.py:44:21-26: Instance-only attribute `a` of class `ChildB` is not visible on the class [missing-attribute]
"""
